INSERT INTO tags (id, name) VALUES (1, 'Волшебный мир');
INSERT INTO tags (id, name) VALUES (2, 'Волшебство');
INSERT INTO tags (id, name) VALUES (3, 'Воровство');
INSERT INTO tags (id, name) VALUES (4, 'Воспитание в приемной семье');
INSERT INTO tags (id, name) VALUES (5, 'Воспитание детей');
INSERT INTO tags (id, name) VALUES (6, 'Воспоминания');
INSERT INTO tags (id, name) VALUES (7, 'Воссоединение девушки и парня');
INSERT INTO tags (id, name) VALUES (8, 'Воссоединение жены и мужа');
INSERT INTO tags (id, name) VALUES (9, 'Воссоединение матери и дочери');
INSERT INTO tags (id, name) VALUES (10, 'Воссоединение матери и сына');
INSERT INTO tags (id, name) VALUES (11, 'Воссоединение отца и дочери');
INSERT INTO tags (id, name) VALUES (12, 'Воссоединение отца и сына');
INSERT INTO tags (id, name) VALUES (13, 'Воссоединение семьи');
INSERT INTO tags (id, name) VALUES (14, 'Восставший из мертвых');
INSERT INTO tags (id, name) VALUES (15, 'Восстание');
INSERT INTO tags (id, name) VALUES (16, 'Врожденные дефекты');
INSERT INTO tags (id, name) VALUES (17, 'Встреча через много лет');
INSERT INTO tags (id, name) VALUES (18, 'Выживание');
INSERT INTO tags (id, name) VALUES (19, 'Выживание среди зомби');
INSERT INTO tags (id, name) VALUES (20, 'Вынужденный брак');
INSERT INTO tags (id, name) VALUES (21, 'Выход в открытый космос');
INSERT INTO tags (id, name) VALUES (22, 'Вечная молодость');
INSERT INTO tags (id, name) VALUES (23, 'Видение будущего');
INSERT INTO tags (id, name) VALUES (24, 'Вирус');
INSERT INTO tags (id, name) VALUES (25, 'Влюбленная женщина');
INSERT INTO tags (id, name) VALUES (26, 'Влюбленные воссоединились');
INSERT INTO tags (id, name) VALUES (27, 'Влюбленный подросток');
INSERT INTO tags (id, name) VALUES (28, 'Военная академия');
INSERT INTO tags (id, name) VALUES (29, 'Военная диктатура');
INSERT INTO tags (id, name) VALUES (30, 'Военная жизнь');
INSERT INTO tags (id, name) VALUES (31, 'Вождь');
INSERT INTO tags (id, name) VALUES (32, 'Возвращение в прошлое');
INSERT INTO tags (id, name) VALUES (33, 'Возвращение к жизни');
INSERT INTO tags (id, name) VALUES (34, 'Возвращение с войны');
INSERT INTO tags (id, name) VALUES (35, 'Возвращенная молодость');
INSERT INTO tags (id, name) VALUES (36, 'Воин');
INSERT INTO tags (id, name) VALUES (37, 'Война');
INSERT INTO tags (id, name) VALUES (38, 'Война против машин');
INSERT INTO tags (id, name) VALUES (39, 'Вокруг Света');
INSERT INTO tags (id, name) VALUES (40, 'Волк');
INSERT INTO tags (id, name) VALUES (41, 'Гадание');
INSERT INTO tags (id, name) VALUES (42, 'Гадкий утенок');
INSERT INTO tags (id, name) VALUES (43, 'Гангстеры');
INSERT INTO tags (id, name) VALUES (44, 'Героизм');
INSERT INTO tags (id, name) VALUES (45, 'Героиня добивается героя');
INSERT INTO tags (id, name) VALUES (46, 'Главный герой циник');
INSERT INTO tags (id, name) VALUES (47, 'Гномы');
INSERT INTO tags (id, name) VALUES (48, 'Говорящие животные');
INSERT INTO tags (id, name) VALUES (49, 'Говорящий с мертвыми');
INSERT INTO tags (id, name) VALUES (50, 'Гонщик');
INSERT INTO tags (id, name) VALUES (51, 'Городская жизнь');
INSERT INTO tags (id, name) VALUES (52, 'Горы');
INSERT INTO tags (id, name) VALUES (53, 'Готика');
INSERT INTO tags (id, name) VALUES (54, 'Готическая субкультура');
INSERT INTO tags (id, name) VALUES (55, 'Гражданская война');
INSERT INTO tags (id, name) VALUES (56, 'Гражданский брак');
INSERT INTO tags (id, name) VALUES (57, 'Граф');
INSERT INTO tags (id, name) VALUES (58, 'Графиня');
INSERT INTO tags (id, name) VALUES (59, 'Греческая богиня');
INSERT INTO tags (id, name) VALUES (60, 'Греческая мифология');
INSERT INTO tags (id, name) VALUES (61, 'Греческий бог');
INSERT INTO tags (id, name) VALUES (62, 'Гробница');
INSERT INTO tags (id, name) VALUES (63, 'Давление общества');
INSERT INTO tags (id, name) VALUES (64, 'Двое против всех');
INSERT INTO tags (id, name) VALUES (65, 'Двойная жизнь');
INSERT INTO tags (id, name) VALUES (66, 'Дворец');
INSERT INTO tags (id, name) VALUES (67, 'Дворянство');
INSERT INTO tags (id, name) VALUES (68, 'Демон');
INSERT INTO tags (id, name) VALUES (69, 'Биокатастрофа');
INSERT INTO tags (id, name) VALUES (70, 'Близнецы');
INSERT INTO tags (id, name) VALUES (71, 'Бог');
INSERT INTO tags (id, name) VALUES (72, 'Бог в теле человека');
INSERT INTO tags (id, name) VALUES (73, 'Бог Зла');
INSERT INTO tags (id, name) VALUES (74, 'Богатая вдова');
INSERT INTO tags (id, name) VALUES (75, 'Богатая девчонка');
INSERT INTO tags (id, name) VALUES (76, 'Богатая женщина');
INSERT INTO tags (id, name) VALUES (77, 'Богатая пара');
INSERT INTO tags (id, name) VALUES (78, 'Богатая семья');
INSERT INTO tags (id, name) VALUES (79, 'Богатство');
INSERT INTO tags (id, name) VALUES (80, 'Богатые и бедные');
INSERT INTO tags (id, name) VALUES (81, 'Богатые родители');
INSERT INTO tags (id, name) VALUES (82, 'Богатый бойфренд');
INSERT INTO tags (id, name) VALUES (83, 'Богатый мальчик');
INSERT INTO tags (id, name) VALUES (84, 'Богатый муж');
INSERT INTO tags (id, name) VALUES (85, 'Богатый ребенок');
INSERT INTO tags (id, name) VALUES (86, 'Болезнь');
INSERT INTO tags (id, name) VALUES (87, 'Борьба за власть');
INSERT INTO tags (id, name) VALUES (88, 'Борьба за выживание');
INSERT INTO tags (id, name) VALUES (89, 'Борьба за землю');
INSERT INTO tags (id, name) VALUES (90, 'Борьба за любовь');
INSERT INTO tags (id, name) VALUES (91, 'Борьба за независимость');
INSERT INTO tags (id, name) VALUES (92, 'Борьба за свободу');
INSERT INTO tags (id, name) VALUES (93, 'Борьба за справедливость');
INSERT INTO tags (id, name) VALUES (94, 'Волк-одиночка');
INSERT INTO tags (id, name) VALUES (95, 'Борьба с самим собой');
INSERT INTO tags (id, name) VALUES (96, 'Борьба с системой');
INSERT INTO tags (id, name) VALUES (97, 'Брак без любви');
INSERT INTO tags (id, name) VALUES (98, 'Брак по расчету');
INSERT INTO tags (id, name) VALUES (99, 'Брак пожилого мужчины и молодой женщины');
INSERT INTO tags (id, name) VALUES (100, 'Брак, как ад');
INSERT INTO tags (id, name) VALUES (101, 'Браконьерство');
INSERT INTO tags (id, name) VALUES (102, 'Брат против брата');
INSERT INTO tags (id, name) VALUES (103, 'Брат, предающий брата');
INSERT INTO tags (id, name) VALUES (104, 'Братоубийство');
INSERT INTO tags (id, name) VALUES (105, 'Братские отношения');
INSERT INTO tags (id, name) VALUES (106, 'Братство');
INSERT INTO tags (id, name) VALUES (107, 'Брачная неверность');
INSERT INTO tags (id, name) VALUES (108, 'Бронзовый век');
INSERT INTO tags (id, name) VALUES (109, 'Бросивший учёбу');
INSERT INTO tags (id, name) VALUES (110, 'В бегах');
INSERT INTO tags (id, name) VALUES (111, 'В поисках правды');
INSERT INTO tags (id, name) VALUES (112, 'Вампиры');
INSERT INTO tags (id, name) VALUES (113, 'Вдова');
INSERT INTO tags (id, name) VALUES (114, 'Вдовец');
INSERT INTO tags (id, name) VALUES (115, 'Ведьма');
INSERT INTO tags (id, name) VALUES (116, 'Великая Отечественная война');
INSERT INTO tags (id, name) VALUES (117, 'Верность');
INSERT INTO tags (id, name) VALUES (118, 'Ветеран');
INSERT INTO tags (id, name) VALUES (119, 'Вечная жизнь');
INSERT INTO tags (id, name) VALUES (120, 'Вечная любовь');
INSERT INTO tags (id, name) VALUES (121, 'Демонизм');
INSERT INTO tags (id, name) VALUES (122, 'Демоническая нежить');
INSERT INTO tags (id, name) VALUES (123, 'Демоническая одержимость');
INSERT INTO tags (id, name) VALUES (124, 'Демонический культ');
INSERT INTO tags (id, name) VALUES (125, 'Денежные проблемы');
INSERT INTO tags (id, name) VALUES (126, 'День рождения');
INSERT INTO tags (id, name) VALUES (127, 'Депрессия');
INSERT INTO tags (id, name) VALUES (128, 'Деревня');
INSERT INTO tags (id, name) VALUES (129, 'Детектив под прикрытием');
INSERT INTO tags (id, name) VALUES (130, 'Детектив-любитель');
INSERT INTO tags (id, name) VALUES (131, 'Дети');
INSERT INTO tags (id, name) VALUES (132, 'Дети в опасности');
INSERT INTO tags (id, name) VALUES (133, 'Детоубийство');
INSERT INTO tags (id, name) VALUES (134, 'Детские воспоминания');
INSERT INTO tags (id, name) VALUES (135, 'Джунгли');
INSERT INTO tags (id, name) VALUES (136, 'Диктатура');
INSERT INTO tags (id, name) VALUES (137, 'Доисторическое существо');
INSERT INTO tags (id, name) VALUES (138, 'Долгие отношения');
INSERT INTO tags (id, name) VALUES (139, 'Дом с привидениями');
INSERT INTO tags (id, name) VALUES (140, 'Драконы');
INSERT INTO tags (id, name) VALUES (141, 'Дружба');
INSERT INTO tags (id, name) VALUES (142, 'Дружба перерастает в любовь');
INSERT INTO tags (id, name) VALUES (143, 'Дуэль');
INSERT INTO tags (id, name) VALUES (144, 'Дьявол');
INSERT INTO tags (id, name) VALUES (145, 'Дьяволица');
INSERT INTO tags (id, name) VALUES (146, 'Дьявольский ребенок');
INSERT INTO tags (id, name) VALUES (147, 'Единственный выживший');
INSERT INTO tags (id, name) VALUES (148, 'Жадность');
INSERT INTO tags (id, name) VALUES (149, 'Жажда власти');
INSERT INTO tags (id, name) VALUES (150, 'Жажда денег');
INSERT INTO tags (id, name) VALUES (151, 'Жажда жизни');
INSERT INTO tags (id, name) VALUES (152, 'Жажда крови');
INSERT INTO tags (id, name) VALUES (153, 'Жажда мести');
INSERT INTO tags (id, name) VALUES (154, 'Жажда независимости');
INSERT INTO tags (id, name) VALUES (155, 'Желание умереть');
INSERT INTO tags (id, name) VALUES (156, 'Желания сбываются');
INSERT INTO tags (id, name) VALUES (157, 'Жена военного');
INSERT INTO tags (id, name) VALUES (158, 'Женатый человек');
INSERT INTO tags (id, name) VALUES (159, 'Женоненавистник');
INSERT INTO tags (id, name) VALUES (160, 'Женская дружба');
INSERT INTO tags (id, name) VALUES (161, 'Женщина-социопат');
INSERT INTO tags (id, name) VALUES (162, 'Жестокость');
INSERT INTO tags (id, name) VALUES (163, 'Заблуждения');
INSERT INTO tags (id, name) VALUES (164, 'Заболевание');
INSERT INTO tags (id, name) VALUES (165, 'Забота');
INSERT INTO tags (id, name) VALUES (166, 'Забота о детях');
INSERT INTO tags (id, name) VALUES (167, 'Забота о животных');
INSERT INTO tags (id, name) VALUES (168, 'Заботливый мужчина');
INSERT INTO tags (id, name) VALUES (169, 'Зависимость');
INSERT INTO tags (id, name) VALUES (170, 'Зависимость от наркотиков');
INSERT INTO tags (id, name) VALUES (171, 'Завоевание');
INSERT INTO tags (id, name) VALUES (172, 'Заговор');
INSERT INTO tags (id, name) VALUES (173, 'Избалованный');
INSERT INTO tags (id, name) VALUES (174, 'Издевательство');
INSERT INTO tags (id, name) VALUES (175, 'Измена');
INSERT INTO tags (id, name) VALUES (176, 'Измена бойфренду');
INSERT INTO tags (id, name) VALUES (177, 'Измена жене');
INSERT INTO tags (id, name) VALUES (178, 'Измена мужу');
INSERT INTO tags (id, name) VALUES (179, 'Изнасилование');
INSERT INTO tags (id, name) VALUES (180, 'Инвалидность');
INSERT INTO tags (id, name) VALUES (181, 'Инопланетная цивилизация');
INSERT INTO tags (id, name) VALUES (182, 'Инопланетное вторжение');
INSERT INTO tags (id, name) VALUES (183, 'Инопланетный монстр');
INSERT INTO tags (id, name) VALUES (184, 'Инопланетный паразит');
INSERT INTO tags (id, name) VALUES (185, 'Инопланетный робот');
INSERT INTO tags (id, name) VALUES (186, 'Инопланетяне');
INSERT INTO tags (id, name) VALUES (187, 'Искатель приключений');
INSERT INTO tags (id, name) VALUES (188, 'Искательница приключений');
INSERT INTO tags (id, name) VALUES (189, 'Испытания на человеке');
INSERT INTO tags (id, name) VALUES (190, 'Казарма');
INSERT INTO tags (id, name) VALUES (191, 'Каннибализм');
INSERT INTO tags (id, name) VALUES (192, 'Карлик');
INSERT INTO tags (id, name) VALUES (193, 'Катаклизм');
INSERT INTO tags (id, name) VALUES (194, 'Киберпреступность');
INSERT INTO tags (id, name) VALUES (195, 'Киберпространство');
INSERT INTO tags (id, name) VALUES (196, 'Киборги');
INSERT INTO tags (id, name) VALUES (197, 'Кладбище');
INSERT INTO tags (id, name) VALUES (198, 'Клятва');
INSERT INTO tags (id, name) VALUES (199, 'Ковбои');
INSERT INTO tags (id, name) VALUES (200, 'Колонизация');
INSERT INTO tags (id, name) VALUES (201, 'Комета');
INSERT INTO tags (id, name) VALUES (202, 'Конец войны');
INSERT INTO tags (id, name) VALUES (203, 'Конец дружбы');
INSERT INTO tags (id, name) VALUES (204, 'Космическая станция');
INSERT INTO tags (id, name) VALUES (205, 'Космическая экспедиция');
INSERT INTO tags (id, name) VALUES (206, 'Космические войны');
INSERT INTO tags (id, name) VALUES (207, 'Космический корабль');
INSERT INTO tags (id, name) VALUES (208, 'Космический монстр');
INSERT INTO tags (id, name) VALUES (209, 'Космический пират');
INSERT INTO tags (id, name) VALUES (210, 'Космический полет');
INSERT INTO tags (id, name) VALUES (211, 'Космическое путешествие');
INSERT INTO tags (id, name) VALUES (212, 'Космическое сражение');
INSERT INTO tags (id, name) VALUES (213, 'Кризис личности');
INSERT INTO tags (id, name) VALUES (214, 'Кризис семейной жизни');
INSERT INTO tags (id, name) VALUES (215, 'Кризис совести');
INSERT INTO tags (id, name) VALUES (216, 'Крик боли');
INSERT INTO tags (id, name) VALUES (217, 'Кругосветное путешествие');
INSERT INTO tags (id, name) VALUES (218, 'Куртизанка/Продажная женщина');
INSERT INTO tags (id, name) VALUES (219, 'Лабораторный эксперимент');
INSERT INTO tags (id, name) VALUES (220, 'Ложные обвинения');
INSERT INTO tags (id, name) VALUES (221, 'Лук и стрелы');
INSERT INTO tags (id, name) VALUES (222, 'Любовная история');
INSERT INTO tags (id, name) VALUES (223, 'Любовная ссора');
INSERT INTO tags (id, name) VALUES (224, 'Любовники');
INSERT INTO tags (id, name) VALUES (225, 'Любовники в бегах');
INSERT INTO tags (id, name) VALUES (226, 'Любовный треугольник');
INSERT INTO tags (id, name) VALUES (227, 'Любовь вопреки всему');
INSERT INTO tags (id, name) VALUES (228, 'Любовь из детства');
INSERT INTO tags (id, name) VALUES (229, 'Любовь между лучшими друзьями');
INSERT INTO tags (id, name) VALUES (230, 'Любовь между человеком и вампиром');
INSERT INTO tags (id, name) VALUES (231, 'Любовь против карьеры');
INSERT INTO tags (id, name) VALUES (232, 'Любовь с первого взгляда');
INSERT INTO tags (id, name) VALUES (233, 'Любовь сквозь время');
INSERT INTO tags (id, name) VALUES (234, 'Маг');
INSERT INTO tags (id, name) VALUES (235, 'Магическая девушка');
INSERT INTO tags (id, name) VALUES (236, 'Магическая книга');
INSERT INTO tags (id, name) VALUES (237, 'Магическая сила');
INSERT INTO tags (id, name) VALUES (238, 'Магический язык');
INSERT INTO tags (id, name) VALUES (239, 'Магическое проклятье');
INSERT INTO tags (id, name) VALUES (240, 'Магия');
INSERT INTO tags (id, name) VALUES (241, 'Магнат');
INSERT INTO tags (id, name) VALUES (242, 'Майя');
INSERT INTO tags (id, name) VALUES (243, 'Маленький город');
INSERT INTO tags (id, name) VALUES (244, 'Маленький король');
INSERT INTO tags (id, name) VALUES (245, 'Малолетний преступник');
INSERT INTO tags (id, name) VALUES (246, 'Маньяк');
INSERT INTO tags (id, name) VALUES (247, 'Марсианин');
INSERT INTO tags (id, name) VALUES (248, 'Марсианская цивилизация');
INSERT INTO tags (id, name) VALUES (249, 'Матерый преступник');
INSERT INTO tags (id, name) VALUES (250, 'Мать');
INSERT INTO tags (id, name) VALUES (251, 'Мать против дочери');
INSERT INTO tags (id, name) VALUES (252, 'Мафия');
INSERT INTO tags (id, name) VALUES (253, 'Мачеха');
INSERT INTO tags (id, name) VALUES (254, 'Мачо');
INSERT INTO tags (id, name) VALUES (255, 'Межгалактичекое путешествие');
INSERT INTO tags (id, name) VALUES (256, 'Международные отношения');
INSERT INTO tags (id, name) VALUES (257, 'Межкультурные отношения');
INSERT INTO tags (id, name) VALUES (258, 'Межпространственное путешествие');
INSERT INTO tags (id, name) VALUES (259, 'Межрасовая дружба');
INSERT INTO tags (id, name) VALUES (260, 'Межрасовая любовь');
INSERT INTO tags (id, name) VALUES (261, 'Межрасовая семья');
INSERT INTO tags (id, name) VALUES (262, 'Межрасовые отношения');
INSERT INTO tags (id, name) VALUES (263, 'Межрасовый брак');
INSERT INTO tags (id, name) VALUES (264, 'Месть');
INSERT INTO tags (id, name) VALUES (265, 'Мечты');
INSERT INTO tags (id, name) VALUES (266, 'Мизантропия');
INSERT INTO tags (id, name) VALUES (267, 'Мировое господство');
INSERT INTO tags (id, name) VALUES (268, 'Мифическое существо');
INSERT INTO tags (id, name) VALUES (269, 'Молодая вдова');
INSERT INTO tags (id, name) VALUES (270, 'Молодая влюбленная пара');
INSERT INTO tags (id, name) VALUES (271, 'Молодежная культура');
INSERT INTO tags (id, name) VALUES (272, 'Монстр');
INSERT INTO tags (id, name) VALUES (273, 'Морская жизнь');
INSERT INTO tags (id, name) VALUES (274, 'Морское чудовище');
INSERT INTO tags (id, name) VALUES (275, 'Морской бог');
INSERT INTO tags (id, name) VALUES (276, 'Мошенничество');
INSERT INTO tags (id, name) VALUES (277, 'Мужская гордость');
INSERT INTO tags (id, name) VALUES (278, 'Мужская дружба');
INSERT INTO tags (id, name) VALUES (279, 'Мужской дух товарищества');
INSERT INTO tags (id, name) VALUES (280, 'Наемный убийца');
INSERT INTO tags (id, name) VALUES (281, 'Наивность');
INSERT INTO tags (id, name) VALUES (282, 'Настойчивость');
INSERT INTO tags (id, name) VALUES (283, 'Недоверие');
INSERT INTO tags (id, name) VALUES (284, 'Нежность');
INSERT INTO tags (id, name) VALUES (285, 'Необычный дар');
INSERT INTO tags (id, name) VALUES (286, 'Неожиданный финал');
INSERT INTO tags (id, name) VALUES (287, 'Неудавшееся самоубийство');
INSERT INTO tags (id, name) VALUES (288, 'Неудавшиеся отношения');
INSERT INTO tags (id, name) VALUES (289, 'Обман');
INSERT INTO tags (id, name) VALUES (290, 'Оборотни');
INSERT INTO tags (id, name) VALUES (291, 'Общение с мертвыми');
INSERT INTO tags (id, name) VALUES (292, 'Общение через интернет');
INSERT INTO tags (id, name) VALUES (293, 'Общественные беспорядки');
INSERT INTO tags (id, name) VALUES (294, 'Оптимизм');
INSERT INTO tags (id, name) VALUES (295, 'От первого лица');
INSERT INTO tags (id, name) VALUES (296, 'Отношения бедного мужчины и богатой женщины');
INSERT INTO tags (id, name) VALUES (297, 'Отношения бедной женщины и богатого мужчины');
INSERT INTO tags (id, name) VALUES (298, 'Отношения более взрослой женщины и мужчины');
INSERT INTO tags (id, name) VALUES (299, 'Отношения брата и сестры');
INSERT INTO tags (id, name) VALUES (300, 'Отношения в семье');
INSERT INTO tags (id, name) VALUES (301, 'Отношения вампира и человека');
INSERT INTO tags (id, name) VALUES (302, 'Отношения взрослого и ребенка');
INSERT INTO tags (id, name) VALUES (303, 'Отношения девушки и ее парня');
INSERT INTO tags (id, name) VALUES (304, 'Отношения женщин');
INSERT INTO tags (id, name) VALUES (305, 'Отношения матери и дочери');
INSERT INTO tags (id, name) VALUES (306, 'Отношения матери и сына');
INSERT INTO tags (id, name) VALUES (307, 'Отношения мачехи и падчерицы');
INSERT INTO tags (id, name) VALUES (308, 'Отношения мачехи и пасынка');
INSERT INTO tags (id, name) VALUES (309, 'Отношения между братьями');
INSERT INTO tags (id, name) VALUES (310, 'Отношения между подругами');
INSERT INTO tags (id, name) VALUES (311, 'Отношения молодой девушки и взрослого мужчины');
INSERT INTO tags (id, name) VALUES (312, 'Отношения мужа и жены');
INSERT INTO tags (id, name) VALUES (313, 'Отношения мужчин');
INSERT INTO tags (id, name) VALUES (314, 'Отношения мужчины и женщины');
INSERT INTO tags (id, name) VALUES (315, 'Отношения на грани любви и ненависти');
INSERT INTO tags (id, name) VALUES (316, 'Отношения на расстоянии');
INSERT INTO tags (id, name) VALUES (317, 'Отношения отца и дочери');
INSERT INTO tags (id, name) VALUES (318, 'Отношения отца и сына');
INSERT INTO tags (id, name) VALUES (319, 'Отношения отчима и падчерицы');
INSERT INTO tags (id, name) VALUES (320, 'Отношения отчима и пасынка');
INSERT INTO tags (id, name) VALUES (321, 'Отношения пожилого мужчины и молодой женщины');
INSERT INTO tags (id, name) VALUES (322, 'Отношения робота и человека');
INSERT INTO tags (id, name) VALUES (323, 'Отношения роботов');
INSERT INTO tags (id, name) VALUES (324, 'Отношения родителей и детей');
INSERT INTO tags (id, name) VALUES (325, 'Отношения сестер');
INSERT INTO tags (id, name) VALUES (326, 'Отношения человека и животного');
INSERT INTO tags (id, name) VALUES (327, 'Отношения человека и инопланетянина');
INSERT INTO tags (id, name) VALUES (328, 'Отчаяние');
INSERT INTO tags (id, name) VALUES (329, 'Охота за сокровищами');
INSERT INTO tags (id, name) VALUES (330, 'Падшая женщина');
INSERT INTO tags (id, name) VALUES (331, 'Падший ангел');
INSERT INTO tags (id, name) VALUES (332, 'Параллельное время');
INSERT INTO tags (id, name) VALUES (333, 'Параллельные миры');
INSERT INTO tags (id, name) VALUES (334, 'Первая любовь');
INSERT INTO tags (id, name) VALUES (335, 'Первое свидание');
INSERT INTO tags (id, name) VALUES (336, 'Пессимизм');
INSERT INTO tags (id, name) VALUES (337, 'Пираты');
INSERT INTO tags (id, name) VALUES (338, 'Поиск любви');
INSERT INTO tags (id, name) VALUES (339, 'Поиск правды');
INSERT INTO tags (id, name) VALUES (340, 'Поиск убийцы');
INSERT INTO tags (id, name) VALUES (341, 'Политика');
INSERT INTO tags (id, name) VALUES (342, 'После ядерной войны');
INSERT INTO tags (id, name) VALUES (343, 'Послевоенное время');
INSERT INTO tags (id, name) VALUES (344, 'Потеря');
INSERT INTO tags (id, name) VALUES (345, 'Потеря дочери');
INSERT INTO tags (id, name) VALUES (346, 'Потеря друга');
INSERT INTO tags (id, name) VALUES (347, 'Потеря жены');
INSERT INTO tags (id, name) VALUES (348, 'Потеря любимого человека');
INSERT INTO tags (id, name) VALUES (349, 'Потеря матери');
INSERT INTO tags (id, name) VALUES (350, 'Потеря младенца');
INSERT INTO tags (id, name) VALUES (351, 'Потеря мужа');
INSERT INTO tags (id, name) VALUES (352, 'Потеря памяти');
INSERT INTO tags (id, name) VALUES (353, 'Потеря подруги');
INSERT INTO tags (id, name) VALUES (354, 'Потеря ребенка');
INSERT INTO tags (id, name) VALUES (355, 'Потеря репутации');
INSERT INTO tags (id, name) VALUES (356, 'Потеря родителей');
INSERT INTO tags (id, name) VALUES (357, 'Потеря сына');
INSERT INTO tags (id, name) VALUES (358, 'Потоп');
INSERT INTO tags (id, name) VALUES (359, 'Похищение');
INSERT INTO tags (id, name) VALUES (360, 'Преданность');
INSERT INTO tags (id, name) VALUES (361, 'Преступная жизнь');
INSERT INTO tags (id, name) VALUES (362, 'Призраки');
INSERT INTO tags (id, name) VALUES (363, 'Провинциальная жизнь');
INSERT INTO tags (id, name) VALUES (364, 'Провинция');
INSERT INTO tags (id, name) VALUES (365, 'Проклятие');
INSERT INTO tags (id, name) VALUES (366, 'Пророчество');
INSERT INTO tags (id, name) VALUES (367, 'Путешествие');
INSERT INTO tags (id, name) VALUES (368, 'Пытка');
INSERT INTO tags (id, name) VALUES (369, 'Разбойники/бандиты');
INSERT INTO tags (id, name) VALUES (370, 'Страх');
INSERT INTO tags (id, name) VALUES (371, 'Волшебники');
INSERT INTO tags (id, name) VALUES (372, 'Воссоединение старых друзей');
INSERT INTO tags (id, name) VALUES (373, 'Галактическая война');
INSERT INTO tags (id, name) VALUES (374, 'Давняя привязанность');
INSERT INTO tags (id, name) VALUES (375, 'Богатый мальчик и бедная девочка');
INSERT INTO tags (id, name) VALUES (376, 'Борьба одиночки');
INSERT INTO tags (id, name) VALUES (377, 'Брак между людьми разных вероисповеданий');
INSERT INTO tags (id, name) VALUES (378, 'Доисторическое животное');
INSERT INTO tags (id, name) VALUES (379, 'Женщина детектив');
INSERT INTO tags (id, name) VALUES (380, 'Иноземная форма жизни');
INSERT INTO tags (id, name) VALUES (381, 'Казанова');
INSERT INTO tags (id, name) VALUES (382, 'Классовая война');
INSERT INTO tags (id, name) VALUES (383, 'Кризис среднего возраста');
INSERT INTO tags (id, name) VALUES (384, 'Магическое заклинание');
INSERT INTO tags (id, name) VALUES (385, 'Межнациональные романтические отношения');
INSERT INTO tags (id, name) VALUES (386, 'Наказание');
INSERT INTO tags (id, name) VALUES (387, 'Ненависть перерастает в любовь');
INSERT INTO tags (id, name) VALUES (388, 'Отношения мальчика и девочки');
INSERT INTO tags (id, name) VALUES (389, 'Первая мировая война');
INSERT INTO tags (id, name) VALUES (390, 'Предательство');
INSERT INTO tags (id, name) VALUES (391, 'Разведенная женщина');
INSERT INTO tags (id, name) VALUES (392, 'Развод');
INSERT INTO tags (id, name) VALUES (393, 'Раздвоение личности');
INSERT INTO tags (id, name) VALUES (394, 'Разлука');
INSERT INTO tags (id, name) VALUES (395, 'Разновозрастные отношения');
INSERT INTO tags (id, name) VALUES (396, 'Разоблачение');
INSERT INTO tags (id, name) VALUES (397, 'Разочарование');
INSERT INTO tags (id, name) VALUES (398, 'Ревнивая жена');
INSERT INTO tags (id, name) VALUES (399, 'Ревнивая женщина');
INSERT INTO tags (id, name) VALUES (400, 'Ревнивый бойфренд');
INSERT INTO tags (id, name) VALUES (401, 'Ревнивый любовник');
INSERT INTO tags (id, name) VALUES (402, 'Ревнивый муж');
INSERT INTO tags (id, name) VALUES (403, 'Ревнивый человек');
INSERT INTO tags (id, name) VALUES (404, 'Ревность');
INSERT INTO tags (id, name) VALUES (405, 'Реинкарнация');
INSERT INTO tags (id, name) VALUES (406, 'Религия');
INSERT INTO tags (id, name) VALUES (407, 'Робинзонада');
INSERT INTO tags (id, name) VALUES (408, 'Роботы');
INSERT INTO tags (id, name) VALUES (409, 'Рождество/Новый год');
INSERT INTO tags (id, name) VALUES (410, 'Рыцари');
INSERT INTO tags (id, name) VALUES (411, 'С постельными сценами');
INSERT INTO tags (id, name) VALUES (412, 'Самоуважение');
INSERT INTO tags (id, name) VALUES (413, 'Самоуверенность');
INSERT INTO tags (id, name) VALUES (414, 'Самоуничтожение');
INSERT INTO tags (id, name) VALUES (415, 'Сатанизм');
INSERT INTO tags (id, name) VALUES (416, 'Сатира');
INSERT INTO tags (id, name) VALUES (417, 'Сатира на общество');
INSERT INTO tags (id, name) VALUES (418, 'Свадьба');
INSERT INTO tags (id, name) VALUES (419, 'Связь с духами');
INSERT INTO tags (id, name) VALUES (420, 'Связь с мертвыми');
INSERT INTO tags (id, name) VALUES (421, 'Семейная вражда');
INSERT INTO tags (id, name) VALUES (422, 'Семейная жизнь');
INSERT INTO tags (id, name) VALUES (423, 'Семейная история');
INSERT INTO tags (id, name) VALUES (424, 'Сирота');
INSERT INTO tags (id, name) VALUES (425, 'Служебный роман');
INSERT INTO tags (id, name) VALUES (426, 'Спорт');
INSERT INTO tags (id, name) VALUES (427, 'Старая дева');
INSERT INTO tags (id, name) VALUES (428, 'Странник');
INSERT INTO tags (id, name) VALUES (429, 'Стремление');
INSERT INTO tags (id, name) VALUES (430, 'Терпение');
INSERT INTO tags (id, name) VALUES (431, 'Терраформирование');
INSERT INTO tags (id, name) VALUES (432, 'Трагедия в прошлом');
INSERT INTO tags (id, name) VALUES (433, 'Тролли');
INSERT INTO tags (id, name) VALUES (434, 'Тюрьма');
INSERT INTO tags (id, name) VALUES (435, 'Тяжелое детство');
INSERT INTO tags (id, name) VALUES (436, 'Убийство');
INSERT INTO tags (id, name) VALUES (437, 'Уродство');
INSERT INTO tags (id, name) VALUES (438, 'Ученые');
INSERT INTO tags (id, name) VALUES (439, 'Феминистка');
INSERT INTO tags (id, name) VALUES (440, 'Физические недостатки');
INSERT INTO tags (id, name) VALUES (441, 'Харизма');
INSERT INTO tags (id, name) VALUES (442, 'Цинизм');
INSERT INTO tags (id, name) VALUES (443, 'Черная магия');
INSERT INTO tags (id, name) VALUES (444, 'Честь');
INSERT INTO tags (id, name) VALUES (445, 'Шантаж');
INSERT INTO tags (id, name) VALUES (446, 'Шпионы');
INSERT INTO tags (id, name) VALUES (447, 'Эгоизм');
INSERT INTO tags (id, name) VALUES (448, 'Эльфы');
INSERT INTO tags (id, name) VALUES (449, 'Эротика');
INSERT INTO tags (id, name) VALUES (450, 'Юмор');
INSERT INTO tags (id, name) VALUES (451, 'Ядерная война');
INSERT INTO tags (id, name) VALUES (452, 'Ядерная зима');
INSERT INTO tags (id, name) VALUES (453, 'Психическое расстройство');
INSERT INTO tags (id, name) VALUES (454, 'Спасение мира');
INSERT INTO tags (id, name) VALUES (455, 'В поисках счастья');
INSERT INTO tags (id, name) VALUES (456, 'Бессмертие');
INSERT INTO tags (id, name) VALUES (457, 'Выживание человечества');
INSERT INTO tags (id, name) VALUES (458, 'Страстная любовь');
INSERT INTO tags (id, name) VALUES (459, 'Фашизм');
INSERT INTO tags (id, name) VALUES (460, 'Вторая мировая война');
INSERT INTO tags (id, name) VALUES (461, 'Суицид');
INSERT INTO tags (id, name) VALUES (462, 'Смерть');
INSERT INTO tags (id, name) VALUES (463, 'Гомосексуализм');
INSERT INTO tags (id, name) VALUES (464, 'Музыка');
INSERT INTO tags (id, name) VALUES (465, 'Противостояние');
INSERT INTO tags (id, name) VALUES (466, 'Тайна');
INSERT INTO tags (id, name) VALUES (467, 'Суперспособность');
INSERT INTO tags (id, name) VALUES (468, 'Экологическая катастрофа');
INSERT INTO genres (id, name) VALUES (1, 'Фантастика');
INSERT INTO genres (id, name) VALUES (2, 'Гуманитарная фантастика');
INSERT INTO genres (id, name) VALUES (3, 'Научная фантастика');
INSERT INTO genres (id, name) VALUES (4, 'Космоопера');
INSERT INTO genres (id, name) VALUES (5, 'Киберпанк');
INSERT INTO genres (id, name) VALUES (6, 'Космическая фантастика');
INSERT INTO genres (id, name) VALUES (7, 'Боевая фантастика');
INSERT INTO genres (id, name) VALUES (8, 'Производственная фантастика');
INSERT INTO genres (id, name) VALUES (9, 'Хроноопера');
INSERT INTO genres (id, name) VALUES (10, 'Постапокалипсис');
INSERT INTO genres (id, name) VALUES (11, 'Роман-катастрофа');
INSERT INTO genres (id, name) VALUES (12, 'Утопия');
INSERT INTO genres (id, name) VALUES (13, 'Антиутопия');
INSERT INTO genres (id, name) VALUES (14, 'Детская фантастика');
INSERT INTO genres (id, name) VALUES (15, 'Попаданцы');
INSERT INTO genres (id, name) VALUES (16, 'Планетарная фантастика');
INSERT INTO genres (id, name) VALUES (17, 'Реализм');
INSERT INTO genres (id, name) VALUES (18, 'Фэнтези');
INSERT INTO genres (id, name) VALUES (19, 'Детское фэнтези');
INSERT INTO genres (id, name) VALUES (20, 'Женское фэнтези');
INSERT INTO genres (id, name) VALUES (21, 'Историческое фэнтези');
INSERT INTO genres (id, name) VALUES (22, 'Эпическое фэнтези');
INSERT INTO genres (id, name) VALUES (23, 'Героическое фэнтези');
INSERT INTO genres (id, name) VALUES (24, 'Городское фэнтези');
INSERT INTO genres (id, name) VALUES (25, 'Научное фэнтези');
INSERT INTO genres (id, name) VALUES (26, 'Технофэнтези');
INSERT INTO genres (id, name) VALUES (27, 'Роман');
INSERT INTO genres (id, name) VALUES (28, 'Дамский детективный роман');
INSERT INTO genres (id, name) VALUES (29, 'Военный роман');
INSERT INTO genres (id, name) VALUES (30, 'Любовный роман');
INSERT INTO genres (id, name) VALUES (31, 'Авантюрный роман');
INSERT INTO genres (id, name) VALUES (32, 'Исторический любовный роман');
INSERT INTO genres (id, name) VALUES (33, 'Короткий любовный роман');
INSERT INTO genres (id, name) VALUES (34, 'Остросюжетный любовный роман');
INSERT INTO genres (id, name) VALUES (35, 'Современный любовный роман');
INSERT INTO genres (id, name) VALUES (36, 'Готический роман');
INSERT INTO genres (id, name) VALUES (37, 'Исторический роман');
INSERT INTO genres (id, name) VALUES (38, 'Любовно-фантастический роман');
INSERT INTO genres (id, name) VALUES (39, 'Эпопея');
INSERT INTO genres (id, name) VALUES (40, 'Романтическая комедия');
INSERT INTO genres (id, name) VALUES (41, 'Постмодернизм');
INSERT INTO genres (id, name) VALUES (42, 'Повесть');
INSERT INTO genres (id, name) VALUES (43, 'Историческая повесть');
INSERT INTO genres (id, name) VALUES (44, 'Фантастическая повесть');
INSERT INTO genres (id, name) VALUES (45, 'Мистика');
INSERT INTO genres (id, name) VALUES (46, 'Детектив');
INSERT INTO genres (id, name) VALUES (47, 'Исторический детектив');
INSERT INTO genres (id, name) VALUES (48, 'Шпионский детектив');
INSERT INTO genres (id, name) VALUES (49, 'Классический детектив');
INSERT INTO genres (id, name) VALUES (50, 'Нуар');
INSERT INTO genres (id, name) VALUES (51, 'Полицейский детектив');
INSERT INTO genres (id, name) VALUES (52, 'Женский детектив');
INSERT INTO genres (id, name) VALUES (53, 'Хоррор/Ужасы');
INSERT INTO genres (id, name) VALUES (54, 'Сказка/Притча');
INSERT INTO genres (id, name) VALUES (55, 'Триллер');
INSERT INTO genres (id, name) VALUES (56, 'Магический реализм');
INSERT INTO genres (id, name) VALUES (57, 'Эротика');
INSERT INTO genres (id, name) VALUES (58, 'Рассказ');
INSERT INTO genres (id, name) VALUES (59, 'Семейный роман/Семейная сага');
INSERT INTO genres (id, name) VALUES (60, 'Боевик');
INSERT INTO genres (id, name) VALUES (61, 'Сюрреализм');
INSERT INTO genres (id, name) VALUES (62, 'Психоделика');
INSERT INTO genres (id, name) VALUES (63, 'Новелла');
INSERT INTO genres (id, name) VALUES (64, 'Мемуары');
INSERT INTO genres (id, name) VALUES (65, 'Трагедия');
INSERT INTO genres (id, name) VALUES (66, 'Стимпанк');
INSERT INTO genres (id, name) VALUES (67, 'Проза');
INSERT INTO genres (id, name) VALUES (68, 'Историческая проза');
INSERT INTO genres (id, name) VALUES (69, 'Классическая проза');
INSERT INTO genres (id, name) VALUES (70, 'Производственная проза');
INSERT INTO genres (id, name) VALUES (71, 'Русская классическая проза');
INSERT INTO genres (id, name) VALUES (72, 'Сентиментальная проза');
INSERT INTO genres (id, name) VALUES (73, 'Советская классическая проза');
INSERT INTO genres (id, name) VALUES (74, 'Современная проза');
INSERT INTO genres (id, name) VALUES (75, 'Юмористическая проза');
INSERT INTO genres (id, name) VALUES (76, 'Детская проза');
INSERT INTO genres (id, name) VALUES (77, 'Остросюжетная проза');
INSERT INTO genres (id, name) VALUES (78, 'Приключения');
INSERT INTO genres (id, name) VALUES (79, 'Детские приключения');
INSERT INTO genres (id, name) VALUES (80, 'Исторические приключения');
INSERT INTO genres (id, name) VALUES (81, 'Морские приключения');
INSERT INTO genres (id, name) VALUES (82, 'Приключения про индейцев');
INSERT INTO genres (id, name) VALUES (83, 'Путешествия и география');
INSERT INTO genres (id, name) VALUES (84, 'Вестерн');
INSERT INTO genres (id, name) VALUES (85, 'Детская остросюжетная литература');
INSERT INTO genres (id, name) VALUES (86, 'Поэзия');
INSERT INTO genres (id, name) VALUES (87, 'Старинная литература');
INSERT INTO genres (id, name) VALUES (88, 'Античная литература');
INSERT INTO genres (id, name) VALUES (89, 'Древневосточная литература');
INSERT INTO genres (id, name) VALUES (90, 'Древнерусская литература');
INSERT INTO genres (id, name) VALUES (91, 'Мифы. Легенды. Эпос');
INSERT INTO genres (id, name) VALUES (92, 'Биография');
INSERT INTO genres (id, name) VALUES (93, 'Графический роман');
INSERT INTO genres (id, name) VALUES (94, 'Манга');
INSERT INTO genres (id, name) VALUES (95, 'Поэма');
INSERT INTO genres (id, name) VALUES (96, 'Пьеса');
INSERT INTO genres (id, name) VALUES (97, 'Нехудожественная литература');
INSERT INTO genres (id, name) VALUES (98, 'Изучение языков');
INSERT INTO genres (id, name) VALUES (99, 'Научно-образовательная литература');
INSERT INTO genres (id, name) VALUES (100, 'Альтернативная медицина');
INSERT INTO genres (id, name) VALUES (101, 'Астрономия и Космос');
INSERT INTO genres (id, name) VALUES (102, 'Биология');
INSERT INTO genres (id, name) VALUES (103, 'Ботаника');
INSERT INTO genres (id, name) VALUES (104, 'Военная история');
INSERT INTO genres (id, name) VALUES (105, 'География');
INSERT INTO genres (id, name) VALUES (106, 'Геология');
INSERT INTO genres (id, name) VALUES (107, 'Государство и право');
INSERT INTO genres (id, name) VALUES (108, 'Детская психология');
INSERT INTO genres (id, name) VALUES (109, 'Зоология');
INSERT INTO genres (id, name) VALUES (110, 'Информатика');
INSERT INTO genres (id, name) VALUES (111, 'История');
INSERT INTO genres (id, name) VALUES (112, 'Культурология');
INSERT INTO genres (id, name) VALUES (113, 'Литературоведение');
INSERT INTO genres (id, name) VALUES (114, 'Математика');
INSERT INTO genres (id, name) VALUES (115, 'Медицина');
INSERT INTO genres (id, name) VALUES (116, 'Научно-популярная литература');
INSERT INTO genres (id, name) VALUES (117, 'Обществознание');
INSERT INTO genres (id, name) VALUES (118, 'Педагогика');
INSERT INTO genres (id, name) VALUES (119, 'Политика');
INSERT INTO genres (id, name) VALUES (120, 'Психология');
INSERT INTO genres (id, name) VALUES (121, 'Религиоведение');
INSERT INTO genres (id, name) VALUES (122, 'Сексология');
INSERT INTO genres (id, name) VALUES (123, 'Техника');
INSERT INTO genres (id, name) VALUES (124, 'Физика');
INSERT INTO genres (id, name) VALUES (125, 'Философия');
INSERT INTO genres (id, name) VALUES (126, 'Химия');
INSERT INTO genres (id, name) VALUES (127, 'Юриспруденция');
INSERT INTO genres (id, name) VALUES (128, 'Языкознание');
INSERT INTO genres (id, name) VALUES (129, 'Компьютерная литература');
INSERT INTO genres (id, name) VALUES (130, 'Графика, дизайн, мультимедиа');
INSERT INTO genres (id, name) VALUES (131, 'Интернет');
INSERT INTO genres (id, name) VALUES (132, 'Компьютеры и программы');
INSERT INTO genres (id, name) VALUES (133, 'Операционные системы');
INSERT INTO genres (id, name) VALUES (134, 'Программирование');
INSERT INTO genres (id, name) VALUES (135, 'Программное обеспечение');
INSERT INTO genres (id, name) VALUES (136, 'Справочная литература');
INSERT INTO genres (id, name) VALUES (137, 'Путеводители');
INSERT INTO genres (id, name) VALUES (138, 'Руководства');
INSERT INTO genres (id, name) VALUES (139, 'Словари');
INSERT INTO genres (id, name) VALUES (140, 'Справочники');
INSERT INTO genres (id, name) VALUES (141, 'Энциклопедии');
INSERT INTO genres (id, name) VALUES (142, 'Документальная литература');
INSERT INTO genres (id, name) VALUES (143, 'Военная документалистика');
INSERT INTO genres (id, name) VALUES (144, 'Искусство и Дизайн');
INSERT INTO genres (id, name) VALUES (145, 'Критика');
INSERT INTO genres (id, name) VALUES (146, 'Публицистика');
INSERT INTO genres (id, name) VALUES (147, 'Религия и духовность');
INSERT INTO genres (id, name) VALUES (148, 'Астрология');
INSERT INTO genres (id, name) VALUES (149, 'Буддизм');
INSERT INTO genres (id, name) VALUES (150, 'Индуизм');
INSERT INTO genres (id, name) VALUES (151, 'Иудаизм');
INSERT INTO genres (id, name) VALUES (152, 'Православие');
INSERT INTO genres (id, name) VALUES (153, 'Религия');
INSERT INTO genres (id, name) VALUES (154, 'Самосовершенствование');
INSERT INTO genres (id, name) VALUES (155, 'Христианство');
INSERT INTO genres (id, name) VALUES (156, 'Эзотерика');
INSERT INTO genres (id, name) VALUES (157, 'Деловая литература');
INSERT INTO genres (id, name) VALUES (158, 'Бизнес');
INSERT INTO genres (id, name) VALUES (159, 'Маркетинг, PR, реклама');
INSERT INTO genres (id, name) VALUES (160, 'Управление, подбор персонала');
INSERT INTO genres (id, name) VALUES (161, 'Ценные бумаги, инвестиции');
INSERT INTO genres (id, name) VALUES (162, 'Экономика');
INSERT INTO genres (id, name) VALUES (163, 'Сентиментализм');
INSERT INTO genres (id, name) VALUES (164, 'Военная литература');
INSERT INTO genres (id, name) VALUES (165, 'Европейская старинная литература');
