name: "user-service"

on:
  push:
    paths:
      - "API/user-service/**"
      - ".github/workflows/user-service.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |-
          cd API/user-service
          mvn -B -DargLine="-ACTIVE_PROFILE=default -CONFIG_URI=http://localhost:8088" package --file pom.xml -DskipTests
  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      ACTIVE_PROFILE: default
      CONFIG_URI: http://localhost:8088
      SPRING_PROFILES_ACTIVE: native
      EUREKA_HOSTNAME: localhost
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run serverconfig
        env:
          SERVER_PORT: 8088
        run: |-
          cd API/serverconfig
          mvn spring-boot:run &
      - name: Run eurekaserver
        run: |-
          cd API/eurekaserver
          mvn spring-boot:run &
      - name: Run gateway-server
        run: |-
          cd API/gateway-server
          mvn spring-boot:run &
      - name: Run tests for user-service
        run: |-
          cd API/user-service
          mvn -B test --file pom.xml

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: user
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: somepassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3